FROM scimulate/code_aster:15.2

# Install Prerequisite Packages
RUN apt-get update && apt-get install -y \
    libmumps-dev \
    libopenblas-dev \
    libparmetis-dev \
    libptscotch-dev \
    libscalapack-*-dev \
    libscotch-dev \
    petsc-dev \
